version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: trade-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SqlStrongPass2026
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P SqlStrongPass2026 -C -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - trade-network

  redis:
    image: redis:alpine
    container_name: trade-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trade-network

  kafka:
    image: apache/kafka:latest
    container_name: trade-kafka
    ports:
      - "9092:9092"
    environment:
      # Configuration KRaft (Sans ZooKeeper)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      # Important : 'localhost' ici permet à votre Spring Boot sur Windows de se connecter
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      # Optimisations pour environnement local (évite les erreurs de réplication)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - trade-network

volumes:
  sqlserver_data:
  redis_data:
  kafka_data:


networks:
  trade-network:
    driver: bridge
